#!/bin/bash

# ngrok authtoken GqcJiYJPvH2hNprQHSyR_47YUE2MSZJGLNv67cP3b6 
# /opt/ngrok http -subdomain=qdraw 80


# /opt/ngrok http -inspect=false -subdomain=qdraw 8080
/opt/ngrok http -subdomain=qdraw 8080

